name: NPM
on:
    pull_request:
    push:
        branches:
            - master
            - feature-*
            - develop
env:
    CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'
    GITHUB_TOKEN: '${{ secrets.REACT_GITHUB_TOKEN }}'
    NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
defaults:
    run:
        shell: bash
jobs:
    test:
        name: Test 🧪
        runs-on: ubuntu-latest
        steps:
            - name: Pre-reqs
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 14.15.0

            - name: Check Cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Test
              run: yarn test

    build:
        name: Build ⚙️
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Pre-reqs
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 12

            - name: Check Cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Build
              run: yarn build

            - name: Save Build
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: ./public/dist

    publish:
        name: Publish 🚀
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Pre-reqs
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: 12

            - name: Check Cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Fetch Build
              uses: actions/download-artifact@v2
              with:
                  name: dist
                  path: ./public/dist

            - name: Run Semantic Release
              id: semantic-release-step
              uses: cycjimmy/semantic-release-action@v2.5.3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Run S3 Upload
              if: steps.semantic-release-step.outputs.new_release_published
              run: yarn deploy-s3 ${{ steps.semantic-release-step.outputs.new_release_version }}
